### ISSUE TITLE
MPI_Sendrecv_replace support is required for CP2K 

### ISSUE THREAD

**Issue by chirag-singh-memverge** [mpickpt/mana#182]
MPI_Sendrecv_replace support is required for certain inputs to CP2K, but the [current implementation](https://github.com/mpickpt/mana/blob/57507e2642114ace56a6a896656866c5c464320c/mpi-proxy-split/mpi-wrappers/mpi_p2p_wrappers.cpp#L210) does not support it.

**Comment by JainTwinkle** [comment]
@xuyao0127 what is the reason behind not supporting `MPI_Sendrecv_replace`? And, how much effort does it require to move and reimplement as the FIXME on L250 suggests?

cc: @gc00

**Comment by xuyao0127** [comment]
The current code in the `MPI_Sendrecv` and `MPI_Sendrecv_replace` wrappers are old codes from Rohan. When we implemented the current point-to-point draining algorithm (commit 59776aeb167f7ffabfa57975c590eb2cfe753caf), we didn't have time to implement new wrappers for these two functions. Since we were only targeting VASP, which doesn't use these two functions, we just added the FIXME comments and assertions that always fail.

To properly implement wrappers for `MPI_Sendrecv` and `MPI_Sendrecv_replace`, I think we can use wrappers for `MPI_Send` and `MPI_Recv` to handle details in point-to-point communications.

**Comment by chirag-singh-memverge** [comment]
Potential fix: https://github.com/chirag-singh-memverge/mana/commit/1385044bfc55b15e4b8c069a3586e0fffb24cdd2

**Comment by JainTwinkle** [comment]
@xuyao0127 Thanks for the explanation! Why do we need to implement it in two parts (send and recv)? What are the implications of calling the actual `MPI_Sendrecv / MPI_Sendrecv_replace` in the lower half?

**Comment by xuyao0127** [comment]
@JainTwinkle `MPI_Sendrecv` and `MPI_Sendrecv_replace` are blocking. Therefore, we can't checkpoint if the program is calling these two functions and blocks. We need to translate them using non-blocking point-to-point communication. Also, to properly drain all point-to-point messages, we need to update several counters in the wrapper functions. So compared to taking care of all details to implement wrappers for  `MPI_Sendrecv` and `MPI_Sendrecv_replace`, using `MPI_Send` and `MPI_Recv` wrappers is easier.

**Comment by JainTwinkle** [comment]
@xuyao0127 Alright! Could you please review https://github.com/chirag-singh-memverge/mana/commit/1385044bfc55b15e4b8c069a3586e0fffb24cdd2?
@chirag-singh-memverge  Could you add the test case for both `MPI_Sendrecv` and `MPI_Sendrev_replace` as well?

**Comment by chirag-singh-memverge** [comment]
https://github.com/chirag-singh-memverge/mana/commit/640eee2abe35055bf8f3acf79866cf2806792669
